### ISSUE TITLE
Prepare for `1.0.0` release

### ISSUE THREAD

**Issue by maciekbanas** [r-world-devs/GitStats#230]
Features:
- [x] #258,
- [x] #199,
- [x] new `add_contributors` function and parameter in `get_repos` function  #235,
- [x] apply GraphQL to GitLab when pulling repositories by organization,
- [x] pass GitLab subgroups (with "/" in name) #176,
- [x] switch engines for repos - e.g. when GraphQL fails, REST is turned on #225,
- [x] switch engines when getting commits #232,
- [x] handle error on adding connections  #242,
- [x] add `web_url` column do repositories  #246,
- [x] fix language functionality #231,
- [x] #268,
- [x] #289,
- [x] #21 ,
- [x] New `get_*_stats()` functions and refactoring plots,

Docs:
- [x] build site for the package,
- [x] update docs [NEWS] after merging features to `devel`.

**Comment by maciekbanas** [comment]
Switching engines done in #227

**Comment by maciekbanas** [comment]
CRAN request will be prepared in one of next releases.
